#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

if [ -z "${DOTFILES:-}" ]; then
  if [ -d "$HOME/.local/share/chezmoi" ]; then
    DOTFILES="$HOME/.local/share/chezmoi"
  else
    DOTFILES="$HOME/.dotfiles"
  fi
fi
export DOTFILES

cd "$DOTFILES"

# Run Homebrew through the Brewfile
echo "› brew bundle"
HOMEBREW_BUNDLE_FILE="${HOMEBREW_BUNDLE_FILE:-$DOTFILES/.Brewfile}" brew bundle

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
